trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build and Publish'
  jobs:
  - job: BuildJob
    displayName: 'Build and Publish Job'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'


- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: DeployJob
    displayName: 'Deploying App to Azure App Service'
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Deploy App to Azure App Service'
      inputs:
        azureSubscription: '<Your-Azure-Subscription-Name>'
        appName: '<Your-Azure-App-Service-Name>'
        appType: 'webApp'
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
        deploymentMethod: 'auto'